name: LaTeX CI

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write  # Required for pushing to gh-pages

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: LaTeX compilation
        uses: dante-ev/latex-action@latest
        with:
          # optional: set up working directory
          # working_directory: 
          # set root file for latex 
          root_file: presentation.tex
          compiler: latexmk
          args: -pdf -file-line-error -interaction=nonstopmode -shell-escape

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: PDF
          # modify name of pdf output accordingly
          path: presentation.pdf
          
      - name: Commit PDF to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git checkout --orphan gh-pages
          git rm -rf .
          cp presentation.pdf out.pdf
          git add out.pdf
          git commit -m "Update PDF"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
